### ISSUE TITLE
Load csv files from realization folders that are not correctly named.

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-subsurface#636] opened 2021-05-07 09:08 UTC
Problem:
Regarding the load_csv function from the _datainput.fmu_input module. One user had created a folder named realization-0_old parallell to the realization-0 folder. In that case it seems to be random which folder was used first and the function gives an error when reading from the "_old" folder since the csv file was not there.

Possible solution:
Ignore folders that are not correctly named and give a warning about it.

**Comment by anders-kiaer** [comment] 2021-05-10 05:36
Is this behaviour due to `webviz-subsurface` or `fmu-ensemble`?

https://github.com/equinor/webviz-subsurface/blob/00418643c004908a351dac3cfc29ced7aab3c196/webviz_subsurface/_datainput/fmu_input.py#L48-L54

https://github.com/equinor/webviz-subsurface/blob/00418643c004908a351dac3cfc29ced7aab3c196/webviz_subsurface/_datainput/fmu_input.py#L23-L35

https://github.com/equinor/webviz-subsurface/blob/00418643c004908a351dac3cfc29ced7aab3c196/webviz_subsurface/_datainput/fmu_input.py#L7

https://github.com/equinor/webviz-subsurface/blob/00418643c004908a351dac3cfc29ced7aab3c196/webviz_subsurface/_datainput/fmu_input.py#L12-L20

**Comment by berland** [comment] 2021-05-10 06:39
The order `realization-0` and `realization-0_old` appears in is due to the filesystem (in practice: random). The order will not matter for fmu-ensemble, but it will not be able to figure out the realization index for `realization-0_old`. I would claim the problem stems from the naming of `realization-0_old` in combination with the filename pattern `realization-*` which I assume is in a config file. A solution would then be to instead name it `old_realization-0`.

**Comment by lindjoha** [comment] 2021-05-10 08:45
Yes, I agree. But is fmu-ensemble reading the realization number from the folder name? In which case, should it give a warning that "0_old" is not a valid realization number?

**Comment by berland** [comment] 2021-05-10 09:20
I guess it does, but that is easily drowns?

**Comment by anders-kiaer** [comment] 2021-05-10 09:28
I also think it would not be catched by the user in most cases (especially if things appears to work - here things did not work downstream, so either the warning was not emitted or it was difficult to see it/understand it).

I'm voting for raising an error if scenarios like the user had here occurs when initializing an ensemble in `fmu-ensemble`, if that is on the table for e.g. `fmu-ensemble` v2? 🙂

**Comment by berland** [comment] 2021-05-11 11:01
I am not convinced this is an error scenario for fmu-ensemble, it is ok to initialize "realizations" from a non-standard realization directory structure.  But webviz can probably filter out realizations where `realization.index is None`. 

Alternatively, a stricter `fnmatch` pattern can be supplied in the yaml? `realization-[?,??,???] `?

**Comment by anders-kiaer** [comment] 2021-06-06 19:36
Dependency-logging did not work as intended before https://github.com/equinor/webviz-config/pull/440. 

The output from `webviz-config` itself is not very verbose (we could also try to further limit it) - i.e. I think the user facing this issue originally would have understood what could be the reason by seeing the `fmu-ensemble` `logging.warning` (which after https://github.com/equinor/webviz-config/pull/440 now correctly surfaces to the terminal). Closing.

**Closed by anders-kiaer** 2021-06-06 19:36 UTC
Labels: bug
